version: '3'
services:
  latex:
    build: .
    image: latex
    container_name: my_latex_container
    volumes: 
      - ./workspace:/workspace/
    command: "latexmk -pdfdvi -f /workspace/test.tex"